name: AlphaSift Daily Stock


on:


  # 手动测试

  workflow_dispatch:



  # 北京时间每天14:30

  # UTC 06:30

  schedule:

    - cron: "30 6 * * 1-5"




jobs:


  run-stock:



    runs-on: ubuntu-latest



    steps:



    # =====================
    # Checkout
    # =====================

    - name: Checkout

      uses: actions/checkout@v5




    # =====================
    # Python
    # =====================

    - name: Setup Python

      uses: actions/setup-python@v6

      with:

        python-version: "3.11"




    # =====================
    # Install
    # =====================

    - name: Install AlphaSift


      run: |


        python -m pip install --upgrade pip

        pip install -e .





    # =====================
    # 显示配置

    # =====================

    - name: Show Config


      run: |


        echo "===================="

        echo "Strategy: ${{ vars.ALPHASIFT_STRATEGY }}"

        echo "LLM Provider: ${{ vars.LLM_PROVIDER }}"

        echo "LLM Model: ${{ vars.LLM_MODEL }}"

        echo "Enable LLM: ${{ vars.ENABLE_LLM }}"

        echo "===================="



    # =====================
    # AlphaSift运行
    # =====================


    - name: Run AlphaSift


      env:


        GEMINI_API_KEY:

          ${{ secrets.GEMINI_API_KEY }}


        DEEPSEEK_API_KEY:

          ${{ secrets.DEEPSEEK_API_KEY }}


        OPENAI_API_KEY:

          ${{ secrets.OPENAI_API_KEY }}



        LLM_PROVIDER:

          ${{ vars.LLM_PROVIDER }}



        LLM_MODEL:

          ${{ vars.LLM_MODEL }}




      run: |


        if [ "${{ vars.ENABLE_LLM }}" = "false" ]

        then


          echo "Run without LLM"


          alphasift screen ${{ vars.ALPHASIFT_STRATEGY }} --no-llm --save-run



        else


          echo "Run with LLM"



          alphasift screen ${{ vars.ALPHASIFT_STRATEGY }} --save-run



        fi






    # =====================
    # 调试输出目录
    # =====================


    - name: Check Result Files


      if: always()


      run: |


        echo "===== FILE LIST ====="


        find . -maxdepth 3 -type f | head -100





    # =====================
    # 上传结果

    # =====================


    - name: Upload Result


      if: always()


      uses: actions/upload-artifact@v6


      with:


        name: alphasift-result-${{ github.run_number }}


        path: |


          reports/


          data/


          runs/







    # =====================
    # 飞书推送

    # =====================


    - name: Send Feishu Report


      if: always()


      env:


        FEISHU_WEBHOOK:

          ${{ secrets.FEISHU_WEBHOOK }}



        ALPHASIFT_STRATEGY:

          ${{ vars.ALPHASIFT_STRATEGY }}



        LLM_MODEL:

          ${{ vars.LLM_MODEL }}



        STATUS:

          ${{ job.status }}



      run: |


        python scripts/send_feishu.py
